version: '2'

services:
  mongo1:
    image: mongo:3.0
    expose:
        - "27017"
    command: mongod --replSet "rs198765"
    depends_on:
      - mongo2
      - mongo3

  mongo2:
    image: mongo:3.0
    expose:
        - "27017"
    command: mongod --replSet "rs198765"

  mongo3:
    image: mongo:3.0
    expose:
      - "27017"
    command: mongod --replSet "rs198765"

  test-mongoose:
    build: .
    ports:
        - "3040:3000"
    volumes:
        - .:/code
        - /code/node_modules
    command: npm run dev
    environment:
        NODE_ENV: 'development'
        MONGO_MAIN_HOSTS: "mongo1:27017,mongo2:27017,mongo3:27017"
    depends_on:
      - mongo1
      - mongo2
      - mongo3
